name: Matrix compatibility

on:
  push:
    branches:
      - version-auto-update

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  go-unit-test:
    name: Generate the compatibility matrix
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: run compat
        run: go run hack/compat-matrix/main.go docs/pages/deploying-vclusters/compat-matrix.mdx
      - name: setup git
        run: |
          git config user.email "bot@loft.sh"
          git config user.name "loft bot"
          git diff --quiet && git diff --staged --quiet || git commit -am 'updated compatibility matrix'
          git push
