name: Matrix compat

on:
  release:
    types: [created]
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "!test/**" # exclude changes in e2e tests
      - ".github/workflows/unit-tests.yaml"
      - "hack/test.sh"
      - "charts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    name: generates automated matrix
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Execute unit tests
        run: just validate-compat-matrix
