name: upgrade test

on:
  release:
    types: [created]
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "!**_test.go" # exclude test files to ignore unit test changes
      - "test/**" # include test files in e2e again
      - "!**.md"
      - "Dockerfile.release"
      - ".github/workflows/e2e.yaml"
      - "charts/**"
      - "manifests/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}-ci:PR${{ github.event.number }}
  VCLUSTER_SUFFIX: vcluster
  VCLUSTER_NAME: vcluster
  VCLUSTER_NAMESPACE: vcluster

jobs:
  build-and-push-syncer-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.21"
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0.15.1
      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true
          version: latest
      - name: Build and save syncer image
        run: |
          set -x
          TELEMETRY_PRIVATE_KEY="" goreleaser build --single-target --snapshot --id vcluster --clean --output ./vcluster
          docker build -t ${{ env.IMAGE_NAME }} -f Dockerfile.release --build-arg TARGETARCH=amd64 --build-arg TARGETOS=linux .
          docker save -o vcluster_syncer ${{ env.IMAGE_NAME }}
      - name: Upload syncer image to artifact
        uses: actions/upload-artifact@v4
        with:
          name: vcluster_syncer
          path: ./vcluster_syncer
          retention-days: 7
  test-upgrade:
    runs-on: ubuntu-latest
    steps:

